#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

function dev {
  lume --dev "$@"
}

function watch {
  lume --dev --watch "$@"
}

function serve {
  lume --dev --serve "$@"
}

function build {
  lume "$@"
}

function sync {
  build
  rsync -a --partial --progress _site/ canvas.rocks:canvas/
}

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | grep -v "^_" | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
